---
- name: Create /etc/flannel
  file:
    path: /etc/flannel
    state: directory
    mode: 0755

- name: Environment Options
  template:
    src: flannel_options_env.j2
    dest: /etc/flannel/options.env
    mode: 0644
  tags: flannel

- name: Drop-in Directory
  file: 
    path: /etc/systemd/system/flanneld.service.d
    state: directory
    mode: 0755
  tags: flannel_systemd
    
- name: Drop-In 40-ExecStartPre-symlink.conf
  template:
    src: 40-ExecStartPre-symlink.conf.j2
    dest: /etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf
    mode: 0644
  notify: 
  - flanneld_systemd
  tags: flannel_dropin

- name: Drop-In 50-network-config.conf
  template:
    src: 50-network-config.conf.j2
    dest: /etc/systemd/system/flanneld.service.d/50-network-config.conf
    mode: 0644
  notify:
  - flanneld_systemd
  tags: flannel_dropin

- name: CNI Configuration Directory
  file:
    path: /etc/kubernetes/cni/net.d
    state: directory
    recurse: true

- name: CNI Configuration
  template:
    src: 10-flannel.conf.j2
    dest: /etc/kubernetes/cni/net.d/10-flannel.conf
    mode: 0644
  tags: flannel_cni
